### ISSUE TITLE
Missing config.txt file

### ISSUE THREAD

**Issue by ManuelSerna** [RaduAlexandru/permuto_sdf#1]
Hello,

Firstly, thank you for publishing the code for this project. 

My issue came up with trying to execute ```build.sh``` in the "docker" folder. Line 9 references a file called ```config.txt``` which does not exist. It seems commenting this line out solves the issue and I was able to train without issues. I am not sure what this file contained or if it was important.

**Comment by takeshie** [comment]
- hi,I meet the same problem.but when I commented the line 9, the build.sh will get error like "build.sh: 12: docker: not found". do you konw how to slove it?

**Comment by RaduAlexandru** [comment]
@ManuelSerna Thanks a lot for pointing out the issue. Indeed the config.txt was not needed anymore and it's just from an older version of the code. I now removed it from build.sh.

@takeshie It seems that you don't have docker installed or at least not everything that is needed for docker. I suggest to check first the installation steps [here](https://docs.docker.com/engine/install/ubuntu/) and the post-instalation steps from [here](https://docs.docker.com/engine/install/linux-postinstall/).
