### ISSUE TITLE
You don't have enough free space in /var/cache/apt/archives/

### ISSUE THREAD

**Issue by sunshineywz123** [RaduAlexandru/permuto_sdf#10]
centos run build.sh
errro
You don't have enough free space in /var/cache/apt/archives/

 ---> 4af3e55f00b8
Step 4/29 : ENV NVIDIA_VISIBLE_DEVICES     ${NVIDIA_VISIBLE_DEVICES:-all}
 ---> Using cache
 ---> 22cd1a3f4f10
Step 5/29 : ENV NVIDIA_DRIVER_CAPABILITIES     ${NVIDIA_DRIVER_CAPABILITIES:+$NVIDIA_DRIVER_CAPABILITIES,}graphics,display,video,utility,compute
 ---> Using cache
 ---> 12c92568102f
Step 6/29 : ENV DEBIAN_FRONTEND noninteractive
 ---> Using cache
 ---> 237c38c718ad
Step 7/29 : ENV PATH="${PATH}:/opt/hpcx/ompi/bin"
 ---> Using cache
 ---> 71433aa01465
Step 8/29 : ENV LD_LIBRARY_PATH="${LD_LIBRARY_PATH}:/opt/hpcx/ompi/lib"
 ---> Using cache
 ---> fe1e4c26949d
Step 9/29 : RUN apt-get -y update && apt-get install -y libassimp-dev libjpeg-dev libpng-dev libglu1-mesa-dev freeglut3-dev mesa-common-dev libgl1-mesa-dev libegl1-mesa-dev sudo
 ---> Using cache
 ---> 6eba853d4c94
Step 10/29 : RUN apt-get -y update   && apt-get install -y -qq --no-install-recommends     libglvnd0     libglx0     libxext6     libx11-6     libglfw3     libglfw3-dev     libpcl-dev     tmux     zip    locate    libboost-program-options-dev    libboost-filesystem-dev    libboost-graph-dev    libboost-system-dev    libboost-test-dev    libeigen3-dev    libsuitesparse-dev    libfreeimage-dev    libmetis-dev    libgoogle-glog-dev    libgflags-dev    libglew-dev    qtbase5-dev    libqt5opengl5-dev    libcgal-dev    libatlas-base-dev    libsuitesparse-dev    libomp-dev    libomp5    imagemagick
 ---> Running in ae4702274fff
Hit:1 http://archive.ubuntu.com/ubuntu focal InRelease
Get:2 http://security.ubuntu.com/ubuntu focal-security InRelease [114 kB]
Get:3 http://archive.ubuntu.com/ubuntu focal-updates InRelease [114 kB]
Get:4 http://archive.ubuntu.com/ubuntu focal-backports InRelease [108 kB]
Fetched 336 kB in 3s (111 kB/s)
Reading package lists...
E: You don't have enough free space in /var/cache/apt/archives/.
The command '/bin/sh -c apt-get -y update   && apt-get install -y -qq --no-install-recommends     libglvnd0     libglx0     libxext6     libx11-6     libglfw3     libglfw3-dev     libpcl-dev     tmux     zip    locate    libboost-program-options-dev    libboost-filesystem-dev    libboost-graph-dev    libboost-system-dev    libboost-test-dev    libeigen3-dev    libsuitesparse-dev    libfreeimage-dev    libmetis-dev    libgoogle-glog-dev    libgflags-dev    libglew-dev    qtbase5-dev    libqt5opengl5-dev    libcgal-dev    libatlas-base-dev    libsuitesparse-dev    libomp-dev    libomp5    imagemagick' returned a non-zero code: 100

**Comment by RaduAlexandru** [comment]
Hi @sunshineywz123 ,

By default docker creates the container inside your root partition. 
It seems your root partition is full or doesn't have enough space in order to  run build.sh.
You can try to make more space by deleting other docker images or unnecessary files.
