### ISSUE TITLE
Failed compiling shader

### ISSUE THREAD

**Issue by jgnooo** [RaduAlexandru/permuto_sdf#24]
When I finished installation and I start the training, compiling shader error was occured.

error message:
[    B6A99740]  Shader.cxx:497    ERR| Error: compiling shader
0:557(2): error: `return' with wrong type int, in function `find_blocker_distance' returning float

I tested in WSL2, and there were no errors during the make.
How can I solve this problem..?

**Comment by RaduAlexandru** [comment]
Hi @jgnooo,

Indeed there was an issue with one of the return values from a shader function. Weirdly enough, this never caused an error on my system as it seems this function was optimized out during shader compilation, so maybe this only happens with WSL?
I pushed a changed that should fix it. Can you please pull easy_pbr and try again?

**Comment by jgnooo** [comment]
Hi,
I'm sorry for late reply.. 

I tested the project in WSL, and the error I said has been solved!
However, the viewer is not worked..
So, I try to install / build in Ubuntu, It finally work

Thank you!!!
