### ISSUE TITLE
Under the big bound box, do the coordinates need to be normalized?

### ISSUE THREAD

**Issue by ZZy129326999** [RaduAlexandru/permuto_sdf#29]
Hello, under the big bound box, do the coordinates need to be normalized?

**Comment by RaduAlexandru** [comment]
Hi @ZZy129326999  

Please apologize my delay. 
The coordinates passed to the permutohedral encoding don't need to be normalized but it's nice to assume that the coordinates are inside a unit sphere as then I can tune the scale of each level of the encoding correctly.

**Comment by ZZy129326999** [comment]
> Hi @ZZy129326999
> 
> Please apologize my delay. The coordinates passed to the permutohedral encoding don't need to be normalized but it's nice to assume that the coordinates are inside a unit sphere as then I can tune the scale of each level of the encoding correctly.

Thank you!!!!
