### ISSUE TITLE
Normalizing camera position without GUI

### ISSUE THREAD

**Issue by MulinYu** [RaduAlexandru/permuto_sdf#7]
Dear Radu,

First of all, thanks for the code and your paper especially the RGB regularization part is impressive.

I am currently attempting to run your code on my own data, which is a large scale scene. However, I have encountered some issues. I tried to obtain the 'scene scale' and 'scene translation' parameters from the geometric measurements of the 'dense point cloud' provided by 'Colmap'. Unfortunately, the results were not satisfactory, with a loss of around '0.1'. It appears that the camera positions are not normalized properly. As I am running the code on a Cluster, I am unable to use your GUI. I was wondering if you had any suggestions on how to check if the camera positions are normalized correctly without using your GUI. Any guidance or advice would be greatly appreciated.

Thank you for your time and assistance.

Best regards.
Mulin

**Comment by MulinYu** [comment]
I found out the solution by using ’save_to_file‘ in easypbr.Mesh class.

**Comment by RaduAlexandru** [comment]
Hi there! 

Currently I don't have an easy way to enable rendering on headless machines. 
I will try soon to add a more automatic way of detecting the correct scale and translation but it might still require some manual tuning depending on your scene. 

As you mentioned, you can try to write your mesh to file  and find their normalization parameters manually. 
Another way would be to open the colmap point cloud and find it's scale and centroid with something like:
```
from easypbr  import *

mesh=Mesh("path_to_colmap_cloud.ply")
centroid=mesh.centroid()
scale=mesh.get_scale()
```
and then use the centroid and scale of the mesh to get your scene within the bounding sphere.

**Comment by sunshineywz123** [comment]
> Hi there!
> 
> Currently I don't have an easy way to enable rendering on headless machines. I will try soon to add a more automatic way of detecting the correct scale and translation but it might still require some manual tuning depending on your scene.
> 
> As you mentioned, you can try to write your mesh to file and find their normalization parameters manually. Another way would be to open the colmap point cloud and find it's scale and centroid with something like:
> 
> ```
> from easypbr  import *
> 
> mesh=Mesh("path_to_colmap_cloud.ply")
> centroid=mesh.centroid()
> scale=mesh.get_scale()
> ```
> 
> and then use the centroid and scale of the mesh to get your scene within the bounding sphere.

. You have to modify this manually for your current dataset using SCENE_SCALE and SCENE_TRANSLATION as it's difficult to provide a reliable and automatic way of selecting these parameters. When you run the run_custom_dataset.py script it will also print the scale and the origin of all the cameras you defined. Note that you don't need to get your cameras to be within the bounding sphere, only the object you want reconstructed needs to be contained within it, the cameras can be outside of the sphere.

the run_custom_dataset.py script print the scale and the originof all the cameras?but we need  the  scale and the originof the object i want reconstructed?

**Comment by sunshineywz123** [comment]
> I found out the solution by using ’save_to_file‘ in easypbr.Mesh class.

how should you do to use the ’save_to_file‘ in easypbr.Mesh class
