### ISSUE TITLE
Missing the horse gallop

### ISSUE THREAD

**Issue by drperpen** [RaduAlexandru/permuto_sdf#8]
Hi,
I am trying to try the ```train_4d_sdf.py``` script but I am missing the mesh sequence. I looked for the "horse_gallop" in the provided link, but all I could find is the other 3 datasets. Can I use a .ply, .obj or any other kind of mesh/ascii sequence format that I can convert to?
Thanks!

```
    permuto_sdf_data
    ├── data_BlendedMVS
    │   ├── bmvs_bear
    │   ├── bmvs_clock
    │   └── ...
    ├── data_DTU
    │   ├── dtu_scan24
    │   ├── dtu_scan37
    │   └── ...
    ├── easy_pbr_renders
    │   ├── head
    ├── horse_gallop
```

**Comment by RaduAlexandru** [comment]
Hi there! 

Thanks for pointing our this issue. I added now the horse gallop dataset to the google drive.
